version: "3.8"

services:
  shortosaur:
    container_name: "shortosaur"
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    environment:
      MONGO_URI: ${MONGO_URI}
      APP_PORT: ${APP_PORT}
    restart: always
    networks:
      - mongo_network

  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_ROOT_DBNAME}
    restart: always
    volumes:
      - mongo_data:/data/shortosaur_db
    networks:
      - mongo_network

volumes:
  mongo_data:

networks:
  mongo_network:
